# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
#npm install and build
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm build
  displayName: 'npm install and build'

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

#install mocha
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --global mocha'

#run test
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'HelloWExpress'
    customCommand: 'run test'

#publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    searchFolder: 'HelloWExpress'

#deploy web app to azure
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure für Bildungseinrichtungen(7123499f-d0d1-457f-8bdd-e36f787e2e0e)'
    appType: 'webApp'
    appName: 'MyMMWebApp'
    package: '$(System.DefaultWorkingDirectory)/HelloWExpress'
    deploymentMethod: 'auto'
