version: '3.7'

services:
  # MySQL DB
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPwd
      MYSQL_DATABASE: myWpDb
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myPwd
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8080:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: myUser
      WORDPRESS_DB_PASSWORD: myPwd
      WORDPRESS_DB_NAME: myWpDb
    networks:
      - wpsite
networks:
  wpsite: